// Writes docs/CODEMAP.md: every top-level function, constant and event handler in js/*.js
// with its line and the comment above it, plus the sections of css/*.css.
// An index for people and AI assistants: find the line, then read only that part of the file.
// Run: npm run map          (writes the file)
//      node tools/codemap.cjs --check   (fails if the map is out of date; part of npm run check)
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const out = path.join(root, "docs", "CODEMAP.md");
const list = (dir, ext) =>
  fs
    .readdirSync(path.join(root, dir))
    .filter((f) => f.endsWith(ext))
    .sort()
    .map((f) => dir + "/" + f);

// the comment directly above line i: "// ..." lines or a one-line "/* ... */"
function commentAbove(lines, i) {
  const got = [];
  for (let j = i - 1; j >= 0; j--) {
    const t = lines[j].trim();
    if (t.includes("====")) break; // the file's banner, not about this name
    if (t.startsWith("//")) got.unshift(t.replace(/^\/\/\s?/, ""));
    else if (/^\/\*.*\*\/$/.test(t))
      got.unshift(t.replace(/^\/\*+\s?|\s?\*+\/$/g, ""));
    else break;
  }
  return clean(got.join(" "));
}
const clean = (s) =>
  s
    .replace(/=+/g, "")
    .replace(/-{3,}/g, "")
    .replace(/\s+/g, " ")
    .replace(/\|/g, "/")
    .trim();
const short = (s, n = 110) => (s.length > n ? s.slice(0, n - 1) + "…" : s);

// the file's own description: the first block comment after "use strict"
function header(lines) {
  let s = "";
  for (let i = 0; i < Math.min(lines.length, 25); i++) {
    const t = lines[i].trim();
    if (!t || t === '"use strict";') continue;
    if (t.startsWith("/*")) {
      let j = i,
        // a "/* ==== title ====" banner with lines under it: the lines say more than the title
        buf = t.includes("====") && !t.includes("*/") ? "" : t;
      while (!lines[j].includes("*/") && j < i + 20) buf += " " + lines[++j];
      s = buf.replace(/^\/\*+|\*+\/$/g, "");
      // a one-line banner followed by // lines: those lines are the description
      if (!s.replace(/[=\s]/g, "") || /^\/\*.*\*\/$/.test(t)) {
        let d = "";
        while (lines[++j] && lines[j].trim().startsWith("//"))
          d += " " + lines[j].trim().replace(/^\/\/\s?/, "");
        if (d) s = d;
      }
    } else if (t.startsWith("//")) {
      let j = i;
      while (lines[j] && lines[j].trim().startsWith("//"))
        s += " " + lines[j++].trim().replace(/^\/\/\s?/, "");
    }
    break;
  }
  return short(clean(s), 300);
}

function mapJS(file) {
  const lines = fs.readFileSync(path.join(root, file), "utf8").split("\n");
  const rows = [];
  lines.forEach((ln, i) => {
    let m, row;
    if ((m = /^(async\s+)?function\s+(\w+)\s*\(([^)]*)\)/.exec(ln)))
      row = `${m[1] ? "async " : ""}${m[2]}(${m[3].replace(/\s+/g, " ").trim()})`;
    else if ((m = /^(?:const|let|var)\s+(\w+)\s*=\s*(async\s*)?(\([^)]*\)|\w+)\s*=>/.exec(ln)))
      row = `${m[1]}${m[3].startsWith("(") ? m[3] : "(" + m[3] + ")"} =>`;
    else if ((m = /^(?:const|let|var)\s+([\w$]+)\s*=/.exec(ln))) row = m[1];
    else if ((m = /^(?:let|var)\s+([\w$]+)\s*[,;]/.exec(ln))) row = m[1];
    else if ((m = /^\$\("([^"]+)"\)\.(on\w+)\s*=/.exec(ln))) row = `on ${m[1]} ${m[2]}`;
    else if ((m = /^(document|window)\.addEventListener\("(\w+)"/.exec(ln)))
      row = `on ${m[1]} ${m[2]}`;
    else if ((m = /^\$\("([^"]+)"\)\.addEventListener\("(\w+)"/.exec(ln)))
      row = `on ${m[1]} ${m[2]}`;
    if (!row) return;
    const c = commentAbove(lines, i);
    rows.push(`- ${i + 1} \`${row}\`${c ? " " + short(c) : ""}`);
  });
  return { lines: lines.length, head: header(lines), rows };
}

function mapCSS(file) {
  const lines = fs.readFileSync(path.join(root, file), "utf8").split("\n");
  const rows = [];
  lines.forEach((ln, i) => {
    const m = /^\/\*\s*(.*?)\s*\*\/$/.exec(ln);
    if (m) rows.push(`${i + 1} ${short(clean(m[1]), 80)}`);
  });
  return { lines: lines.length, rows };
}

function build() {
  let s = `# Code map

Generated by \`npm run map\` (tools/codemap.cjs). Do not edit by hand: \`npm run check\` fails when it is out of date.

How to use it: find the name here, then read only those lines (\`Read file offset=<line>\`), or grep for the name.
All \`js/*.js\` share one global scope and load in filename order (see CLAUDE.md), so a name is unique across files.
Rows: line number, name (functions with their arguments, \`=>\` for arrow functions, \`on #id event\` for handlers), the comment above it.

## Where things are wired (read this before searching)

| To change | Look at |
|---|---|
| A page or section in the navigation | \`NAV\` in js/12-views.js; \`setView(v)\`; pages render from \`renderAll()\` (16-app) |
| What is drawn on the layout | \`buildSVG(sh, o)\` in 07-canvas: areas, fixed, tape, items, overlay, routes, then \`labelsSVG\` names, pins, selection |
| Names on the drawing | \`labelsSVG\` in 37-labels (inside the item, else a tag with a leader line) |
| A button in the layout side panel | its \`data-a="..."\` value, handled in \`act()\` (08-actions) |
| Saved data shape | \`validate(p)\` in 05-storage: bump \`p.version\` and \`version\` in \`projectBundle()\` (14), migrate old shapes, keep old fixtures opening |
| A dialog | \`modal(title, html, ok, opts)\` (06); its body is fresh each time |
| Anything printed | \`printWithPage(html, cls, pageCss)\` (06); A3 and A4 |
| Keyboard shortcuts | \`document keydown\` in 15-settings-keyboard; the list in \`shortcutsModal()\` (37-layout-edit) |
| Showing picker (factory / line / zone) | \`setScope\`, \`scopeArea\`, \`scopeObj\` in 34-areas |
| Styles | the css/ files listed at the end; each section starts with a \`/* title */\` comment |

`;
  for (const f of list("js", ".js")) {
    const m = mapJS(f);
    s += `## ${f} (${m.lines} lines)\n${m.head ? m.head + "\n" : ""}\n${m.rows.join("\n")}\n\n`;
  }
  s += "## css (sections: line, title)\n\n";
  for (const f of list("css", ".css")) {
    const m = mapCSS(f);
    s += `- **${f}** (${m.lines} lines): ${m.rows.join(" · ")}\n`;
  }
  return s;
}

const text = build();
if (process.argv.includes("--check")) {
  const cur = fs.existsSync(out) ? fs.readFileSync(out, "utf8") : "";
  if (cur !== text) {
    console.error("docs/CODEMAP.md is out of date: run npm run map");
    process.exit(1);
  }
} else {
  fs.writeFileSync(out, text);
  console.log("wrote docs/CODEMAP.md", text.length, "chars");
}
